### ISSUE TITLE
[Help] Is local playlist file supported now?

### ISSUE THREAD

**Issue by jaybowang** [whatcould/playlist-test#1]
I got the same error.

Is local playlist file supported now?
If not, is there any alternative solution?
How do you solve it? Or it just cannot be solved?

Thanks so much.

**Comment by whatcould** [comment]
I heard back from Apple — apparently this method, of creating a local playlist on the fly, was never supported. Though it was only with iOS 9 that it stopped working.

Not very helpful, but at least now we know why.
